[fonts]
size = 18
family = "0xProto Nerd Font Mono"
# family = "Helvetica"

# fonts.extras = [{ family = "Symbols Nerd Font Mono" }]
fonts.emoji = [{ family = "Helvetica" }]

fonts.use-drawable-chars = true

[colors]
cursor = "#ffb060"

[navigation]
mode = "Plain"

# [window]
# mode = "Fullscreen"

[window.background-image]
path = "/Users/mantas/.config/rio/fortune.jpeg"

[editor]
program = "/opt/homebrew/bin/nvim"
