[fonts]
size = 18
family = "0xProto Nerd Font"

[colors]
cursor = "#ffb060"

[navigation]
mode = "Plain"

# [window]
# mode = "Fullscreen"

[bindings]
keys = [
  { key = "a", with = "control", action = "Run(mkdir ~/repos/thisworked)" },
]

[window.background-image]
path = "/Users/mantas/.config/rio/fortune.jpeg"

[editor]
program = "/opt/homebrew/bin/nvim"
