[fonts]
size = 18
family = "0xProto Nerd Font"

[colors]
cursor = "#ffb060"

[navigation]
mode = "Bookmark"

# [window]
# mode = "Fullscreen"

[window.background-image]
path = "/Users/mantas/.config/rio/fortune.jpeg"

[editor]
program = "/opt/homebrew/bin/nvim"
